<?php

namespace Database\Seeders;

use App\Models\Province;
use App\Models\City;
use Illuminate\Database\Seeder;

class ProvinceSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $provinces = [
            'Aceh' => [
                'Banda Aceh',
                'Sabang',
                'Lhokseumawe',
                'Langsa',
                'Aceh Besar',
                'Aceh Singkil',
                'Aceh Selatan',
                'Aceh Tenggara',
                'Aceh Timur',
                'Aceh Utara',
                'Aceh Barat',
                'Aceh Barat Daya',
                'Aceh Jaya',
                'Nagan Raya',
                'Gayo Lues',
                'Bireuen',
                'Aceh Pidie',
                'Pidie Jaya'
            ],
            'Sumatera Utara' => [
                'Medan',
                'Binjai',
                'Pematangsiantar',
                'Tebing Tinggi',
                'Deli Serdang',
                'Langkat',
                'Batubara',
                'Asahan',
                'Labuhan Batu',
                'Labuhan Batu Selatan',
                'Labuhan Batu Utara',
                'Serdang Bedagai',
                'Batu Bara',
                'Dairi',
                'Karo',
                'Simalungun',
                'Tapanuli Selatan',
                'Tapanuli Tengah',
                'Tapanuli Utara',
                'Samosir',
                'Mandailing Natal',
                'Nias',
                'Nias Selatan',
                'Nias Utara',
                'Nias Barat',
                'Sibolga'
            ],
            'Sumatera Barat' => [
                'Padang',
                'Bukittinggi',
                'Payakumbuh',
                'Pariaman',
                'Pesisir Selatan',
                'Solok',
                'Solok Selatan',
                'Kepulauan Mentawai',
                'Limapuluh Kota',
                'Pasaman',
                'Pasaman Barat',
                'Agam',
                'Lima Puluh Kota',
                'Sawahlunto',
                'Sijunjung'
            ],
            'Riau' => [
                'Pekanbaru',
                'Dumai',
                'Kuantan Singingi',
                'Indragiri Hulu',
                'Indragiri Hilir',
                'Pelalawan',
                'Siak',
                'Kampar',
                'Rokan Hilir',
                'Rokan Hulu',
                'Bengkalis',
                'Meranti'
            ],
            'Jambi' => [
                'Jambi',
                'Sungaipenuh',
                'Ogan Ilir',
                'Ogan Komering Ilir',
                'Bungo',
                'Tanjung Jabung Barat',
                'Tanjung Jabung Timur',
                'Kerinci',
                'Merangin',
                'Sarolangun',
                'Tebo'
            ],
            'Sumatera Selatan' => [
                'Palembang',
                'Prabumulih',
                'Lubuklinggau',
                'Muba',
                'Lahat',
                'Penukal Abab Lematang Ilir',
                'Muara Enim',
                'Ogan Komering Ulu',
                'Ogan Komering Ulu Timur',
                'Ogan Komering Ulu Selatan',
                'Banyu Asin',
                'Empat Lawang'
            ],
            'Bengkulu' => [
                'Bengkulu',
                'Curup',
                'Kepahiang',
                'Rejang Lebong',
                'Bengkulu Selatan',
                'Bengkulu Utara',
                'Kaur',
                'Lebong',
                'Mukomuko',
                'Seluma'
            ],
            'Lampung' => [
                'Bandar Lampung',
                'Lampung Barat',
                'Lampung Selatan',
                'Lampung Tengah',
                'Lampung Timur',
                'Lampung Utara',
                'Pesisir Barat',
                'Tanggamus',
                'Tulang Bawang',
                'Tulang Bawang Barat',
                'Way Kanan',
                'Pringsewu',
                'Mesuji'
            ],
            'Kepulauan Bangka Belitung' => [
                'Pangkalpinang',
                'Bangka',
                'Bangka Barat',
                'Bangka Tengah',
                'Bangka Selatan',
                'Belitung',
                'Belitung Timur'
            ],
            'Kepulauan Riau' => [
                'Batam',
                'Tanjung Pinang',
                'Karimun',
                'Bintan',
                'Lingga',
                'Natuna'
            ],
            'DKI Jakarta' => [
                'Jakarta Selatan',
                'Jakarta Barat',
                'Jakarta Pusat',
                'Jakarta Timur',
                'Jakarta Utara',
                'Kepulauan Seribu'
            ],
            'Jawa Barat' => [
                'Bandung',
                'Banjar',
                'Bekasi',
                'Bogor',
                'Cilegon',
                'Cimahi',
                'Depok',
                'Sukabumi',
                'Tasikmalaya',
                'Bogor',
                'Bekasi',
                'Bandung Barat',
                'Ciamis',
                'Cianjur',
                'Cirebon',
                'Garut',
                'Indramayu',
                'Karawang',
                'Kuningan',
                'Majalengka',
                'Pangandaran',
                'Purwakarta',
                'Subang',
                'Sumedang',
                'Tasikmalaya'
            ],
            'Jawa Tengah' => [
                'Semarang',
                'Magelang',
                'Pekalongan',
                'Salatiga',
                'Surakarta',
                'Tegal',
                'Ambarawa',
                'Batang',
                'Blora',
                'Boyolali',
                'Brebes',
                'Demak',
                'Grobogan',
                'Jepara',
                'Karanganyar',
                'Kendal',
                'Klaten',
                'Kudus',
                'Limpopo',
                'Magelang',
                'Pati',
                'Pekalongan',
                'Pemalang',
                'Purbalingga',
                'Purwodadi',
                'Rembang',
                'Sragen',
                'Sukoharjo',
                'Temanggung',
                'Tegal',
                'Wonogiri',
                'Wonosobo'
            ],
            'DI Yogyakarta' => [
                'Yogyakarta',
                'Sleman',
                'Bantul',
                'Gunung Kidul',
                'Kulon Progo'
            ],
            'Jawa Timur' => [
                'Surabaya',
                'Batu',
                'Blitar',
                'Bojonegoro',
                'Bondowoso',
                'Gresik',
                'Jombang',
                'Kediri',
                'Lamongan',
                'Lumajang',
                'Madiun',
                'Magetan',
                'Malang',
                'Mojokerto',
                'Nganjuk',
                'Ngawi',
                'Pacitan',
                'Pamekasan',
                'Pasuruan',
                'Ponorogo',
                'Probolinggo',
                'Sampang',
                'Sidoarjo',
                'Situbondo',
                'Sumenep',
                'Trenggalek',
                'Tuban',
                'Tulungagung'
            ],
            'Banten' => [
                'Serang',
                'Cilegon',
                'Tangerang',
                'Tangerang Selatan',
                'Lebak',
                'Pandeglang',
                'Tangerang',
                'Serang'
            ],
            'Bali' => [
                'Denpasar',
                'Badung',
                'Bangli',
                'Buleleng',
                'Gianyar',
                'Jembrana',
                'Karangasem',
                'Klungkung',
                'Tabanan'
            ],
            'Nusa Tenggara Barat' => [
                'Mataram',
                'Bima',
                'Lombok Barat',
                'Lombok Tengah',
                'Lombok Timur',
                'Lombok Utara',
                'Sumbawa',
                'Sumbawa Barat',
                'Dompu'
            ],
            'Nusa Tenggara Timur' => [
                'Kupang',
                'Flores Timur',
                'Ende',
                'Ngada',
                'Manggarai',
                'Manggarai Barat',
                'Manggarai Timur',
                'Rote Ndao',
                'Sabu Raijua',
                'Sikka',
                'Sumba Barat',
                'Sumba Barat Daya',
                'Sumba Timur',
                'Sumba Tengah'
            ],
            'Kalimantan Barat' => [
                'Pontianak',
                'Singkawang',
                'Bengkayang',
                'Capuas Hulu',
                'Ketapang',
                'Kubu Raya',
                'Landak',
                'Mempawah',
                'Sambas',
                'Sanggau',
                'Sekadau',
                'Sintang'
            ],
            'Kalimantan Tengah' => [
                'Palangkaraya',
                'Gunung Mas',
                'Kapuas',
                'Katingan',
                'Kotawaringin Barat',
                'Kotawaringin Timur',
                'Lamandau',
                'Murung Raya',
                'Pulang Pisau',
                'Sukamara',
                'Seruyan'
            ],
            'Kalimantan Selatan' => [
                'Banjarmasin',
                'Banjarbaru',
                'Balangan',
                'Banjar',
                'Hulu Sungai Selatan',
                'Hulu Sungai Tengah',
                'Hulu Sungai Utara',
                'Kotabaru',
                'Tabalong',
                'Tanah Bumbu',
                'Tanah Laut'
            ],
            'Kalimantan Timur' => [
                'Samarinda',
                'Balikpapan',
                'Bontang',
                'Berau',
                'Kutai Barat',
                'Kutai Kartanegara',
                'Kutai Timur',
                'Pasir',
                'Penajam Paser Utara'
            ],
            'Kalimantan Utara' => [
                'Tanjung Selor',
                'Tarakan',
                'Bulungan',
                'Malinau',
                'Nunukan',
                'Tana Tidung'
            ],
            'Sulawesi Utara' => [
                'Manado',
                'Bitung',
                'Tomohon',
                'Bolaang Mongondow',
                'Bolaang Mongondow Timur',
                'Bolaang Mongondow Selatan',
                'Bolaang Mongondow Utara',
                'Kepulauan Sangihe',
                'Kepulauan Talaud',
                'Manado',
                'Minahasa',
                'Minahasa Selatan',
                'Minahasa Utara'
            ],
            'Sulawesi Tengah' => [
                'Palu',
                'Banggai',
                'Banggai Kepulauan',
                'Buol',
                'Donggala',
                'Morowali',
                'Morowali Utara',
                'Parigi Moutong',
                'Poso',
                'Tojo Una-Una',
                'Tolitoli'
            ],
            'Sulawesi Selatan' => [
                'Makassar',
                'Palopo',
                'Parepare',
                'Bantaeng',
                'Barru',
                'Bone',
                'Bulukumba',
                'Enrekang',
                'Gowa',
                'Jeneponto',
                'Kepulauan Selayar',
                'Luwu',
                'Luwu Timur',
                'Luwu Utara',
                'Maros',
                'Pangkajene Kepulauan',
                'Pinrang',
                'Sidenreng Rappang',
                'Sinjai',
                'Soppeng',
                'Takalar',
                'Tana Toraja',
                'Toraja Utara',
                'Wajo'
            ],
            'Sulawesi Tenggara' => [
                'Kendari',
                'Baubau',
                'Bombana',
                'Buton',
                'Buton Selatan',
                'Buton Utara',
                'Kolaka',
                'Kolaka Timur',
                'Kolaka Utara',
                'Konawe',
                'Konawe Selatan',
                'Konawe Utara',
                'Muna',
                'Muna Barat',
                'Wakatobi'
            ],
            'Gorontalo' => [
                'Gorontalo',
                'Boalemo',
                'Bone Bolango',
                'Gorontalo Utara',
                'Pohuwato'
            ],
            'Sulawesi Barat' => [
                'Mamuju',
                'Mamasa',
                'Mamuju Tengah',
                'Mamuju Utara',
                'Polewali Mandar'
            ],
            'Maluku' => [
                'Ambon',
                'Tual',
                'Buru',
                'Buru Selatan',
                'Maluku Barat Daya',
                'Maluku Tengah',
                'Maluku Tenggara',
                'Maluku Tenggara Barat',
                'Seram Bagian Barat',
                'Seram Bagian Timur'
            ],
            'Maluku Utara' => [
                'Ternate',
                'Tidore Kepulauan',
                'Halmahera Barat',
                'Halmahera Selatan',
                'Halmahera Tengah',
                'Halmahera Timur',
                'Halmahera Utara',
                'Kepulauan Sula',
                'Morotai'
            ],
            'Papua' => [
                'Jayapura',
                'Abepura',
                'Biak',
                'Jayawijaya',
                'Jaya Pura',
                'Keerom',
                'Kepulauan Yapen',
                'Lanny Jaya',
                'Mamberamo Raya',
                'Mamberamo Tengah',
                'Merauke',
                'Mimika',
                'Nabire',
                'Paniai',
                'Pegunungan Bintang',
                'Sarmi',
                'Supiori',
                'Tolikara',
                'Waropen',
                'Yalimo'
            ],
            'Papua Barat' => [
                'Manokwari',
                'Sorong',
                'Sorong Selatan',
                'Sorong Utara',
                'Tambrauw',
                'Teluk Bintuni',
                'Teluk Wondama',
                'Raja Ampat',
                'Maybrat'
            ],
            'Papua Selatan' => [
                'Merauke',
                'Buru',
                'Asmat',
                'Mappi'
            ],
            'Papua Tengah' => [
                'Jayapura',
                'Sarmi',
                'Keerom'
            ],
            'Papua Pegunungan' => [
                'Jaya Pura',
                'Lanny Jaya',
                'Jayawijaya',
                'Tolikara'
            ]
        ];

        foreach ($provinces as $provinceName => $cities) {
            $province = Province::create(['name' => $provinceName]);

            foreach ($cities as $cityName) {
                City::create([
                    'province_id' => $province->id,
                    'name' => $cityName
                ]);
            }
        }
    }
}
